### ISSUE TITLE
Permission denied /var/mail

### ISSUE THREAD

**Issue by legrosf** [teid/dovecot-ldap#1]
When i try to log with my account using Rainloop for exemple, the authentication failed. 

 In the Dovecot log file i have this error:

"Initialization failed: Namespace '': mkdir(/var/mail/0/jessie) failed: Permission denied (euid=1000(<unknown>) egid=1000(<unknown>) missing +w perm: /var/mail, we're not in group 0(root), dir owned by 0:0 mode=0775)"

I can make it work with "chmod 777 /var/mail" but everytime i deploy this image i have to do this ...

Do you have any solution ?

**Comment by teid** [comment]
The container does not use per user uid/gid.
As they are probably going to be virtual users, single uid(1000) and gid(8:mail) are used.

The LDAP connector is overriding those default values when it finds the fields uidNumber and gidNumber in the LDAP record.

I've just pushed a fix to avoid the override (4337666)

Let me know if you're still facing the issue after the upgrade

You will need to remove the existing mailboxes or do a `chown -R 1000:mail` on the folder
